### ISSUE TITLE
Update file inputs with accept attribute

### ISSUE THREAD

**Issue by iarkaroy** [pd-25/sustaintel#2]
Please update all file inputs that are supposed to allow only images with accept attribute, e. g. `accept="image/*"`. Also put file validation for images in controller. https://laravel.com/docs/11.x/validation#validating-files

**Comment by pd-25** [comment]
It is added Take a pull from master and hit in browser  /optimize and then /storage (eg. www.abc.com/optimize and then  www.abc.com/storage)
