### ISSUE TITLE
Please check why news thumb not showing

### ISSUE THREAD

**Issue by iarkaroy** [pd-25/sustaintel#3]
The thumb/image of an news entry is not displaying. Please check what is going on. I tried to update the image. It seems the image is getting updated but still not showing.

![2024-06-07_15-26](https://github.com/pd-25/sustaintel/assets/7873091/430ba945-244a-40b5-b150-59773ec3cd14)

**Comment by iarkaroy** [comment]
The image url is getting a 404.

**Comment by pd-25** [comment]
If  this thing is only for that particular data and rest is fine, then re update and check, might be some storage issue. still Take a pull from master and hit in browser  /optimize and then /storage (eg. www.abc.com/optimize and then  www.abc.com/storage)
