### ISSUE TITLE
Error in contact form submit

### ISSUE THREAD

**Issue by iarkaroy** [pd-25/sustaintel#5]
The following error is displayed when submitting the contact form.

![WhatsApp Image 2024-06-07 at 15 34 04](https://github.com/pd-25/sustaintel/assets/7873091/618e13ce-f152-4a9e-8016-26c6d1d34ad3)

Please check the route declaration.

Also phone and email should be properly validated wherever those are accepted.

**Comment by pd-25** [comment]
Change the MAIL_FROM_ADDRESS value in .env with your actual mail address

**Comment by pd-25** [comment]
Update the  MAIL_FROM_ADDRESS value in .env with your actual email. Take a pull from master and hit in browser  /optimize and then /storage (eg. www.abc.com/optimize and then  www.abc.com/storage)
